# -*- coding: utf-8 -*-
"""S08_Atividade.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QTRUvC3EXZpmxdylp1-z1H-wFpbwc-40

# **Semanas 08: Pré-Processamento de Dados I**
## **Atividade Semanal**

> Esta é atividade semanal sugerida. Você deverá preenchê-la e enviá-la dentro do prazo (até o fechamento da semana corrente).
"""

# NAO ALTERE OS COMANDOS ABAIXO
import gdown
import pandas as pd

url = 'https://drive.google.com/uc?id=1DwqWeEuzjuMn_WAmz7U3Uo49I1zeaZyg'
output = 'MFGEmployees4.xlsx'
gdown.download(url, output, quiet=True)

dados_funcionarios = pd.read_excel('/content/MFGEmployees4.xlsx')

"""###Questão 1

Verifique se há registros duplicados na base. Caso positivo, remova-os.
"""

display(dados_funcionarios)  # Mostra o dataframe original
print(dados_funcionarios.duplicated().any())  # Verifica se existem duplicados (True/False)
print(dados_funcionarios.duplicated().sum())  # Conta quantos registros duplicados existem
display(dados_funcionarios[dados_funcionarios.duplicated()])  # Mostra os duplicados

# Criando um novo dataframe sem duplicados
df_dados_funcionarios = dados_funcionarios.drop_duplicates()
display(df_dados_funcionarios)

"""###Questão 2

Verifique se há valores ausentes na base. Caso positivo, remova-os.
"""

# Verifica valores ausentes no dataframe já limpo de duplicadas
df_dados_funcionarios.isna().sum()

# Remove valores ausentes usando o dataframe sem duplicadas
df_dados_funcionarios = df_dados_funcionarios.dropna()

display(df_dados_funcionarios)

"""###Questão 3

Há variáveis que funcionam como "rótulos" nesta base. Quais são? Remova-as
"""

# Visualiza todas as colunas e tipos
df_dados_funcionarios.info()

# Remover colunas de identificação
df_dados_funcionarios = df_dados_funcionarios.drop(columns=['id','sobrenome','nome'])

# Conferir as colunas restantes
df_dados_funcionarios.columns

"""###Questão 4

Existem valores suspeitos ou discrepantes para alguma variável? Caso positivo, remova-os.

Por lei:
*     A idade mínima de um funcionário é 14 anos e máxima é de 80 anos.
*     A duração do serviço não pode ultrapassar 44 horas.
"""

# Questao 4
print(df_dados_funcionarios.describe())
df_dados_funcionarios = df_dados_funcionarios[(df_dados_funcionarios['idade'] >= 14) &
                                              (df_dados_funcionarios['idade'] <= 80)]
df_dados_funcionarios = df_dados_funcionarios[df_dados_funcionarios['duracao_servico'] <= 44]
print(df_dados_funcionarios.describe())